### PR TITLE
update for armhf

### PR DESCRIPTION
**Pull request by sndnvaps**
make it can build in Raspberry pi 
Bind the samba port to docker-compose.yml
Test  system is Ubuntu mate 16.04

Signed-off-by: sndnvaps <sndnvaps@gmail.com>

### CODE REVIEW

**Comment by dperson** [comment]
If it builds on a raspberry pi directly, it can't build on the docker infrastructure (they only have x86_64 systems). So no, I'm not merging the changes to the `Dockerfile`.

What errors are you getting when trying to start the container with the root read only? I'll happily fix those, but have no intention of changing the default.

Adding the ports to the default compose file I'm happy to do.

**Comment by sndnvaps** [comment]
when read_only : true
```
docker-compose up
errors:
root@sn-desktop:~/samba# docker-compose up
Creating network "samba_default" with the default driver
Creating samba_samba_1
Attaching to samba_samba_1
samba_1  | adduser: /etc/passwd: Read-only file system
samba_1  | mkdir failed on directory /var/cache/samba/msg.lock: Read-only file system
samba_1  | smbpasswd is not able to initialize the messaging context!
samba_1  | mkdir failed on directory /var/log/samba/cores: Read-only file system
samba_1  | Failed to create /var/log/samba/cores for user 0 with mode 0700
samba_1  | Unable to setup corepath for smbd: Read-only file system
samba_1  | smbd version 4.8.4 started.
samba_1  | Copyright Andrew Tridgell and the Samba Team 1992-2018
samba_1  | mkdir failed on directory /var/cache/samba/msg.lock: Read-only file system
samba_samba_1 exited with code 1
```

my docker-compose.yml file is 

```
version: '2.0'

services:
  samba:
    build: .
    environment:
      TZ: 'EST5EDT'
    networks:
      - default
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - "139:139/tcp"
      - "137:137/udp"
      - "138:138/udp"
      - "445:445/tcp"
    volumes:
      - /home/sn/share:/mnt:z
    command: '-u "sn;447826004" -s "Mount;/mnt;yes;no;no;sn;sn"'

networks:
  default:
```

docker-compose version 
```
root@sn-desktop:~/samba# docker-compose version
docker-compose version 1.8.0, build unknown
docker-py version: 1.9.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
```

docker version 
```
root@sn-desktop:~/samba# docker version
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:56:41 2018
 OS/Arch:           linux/arm
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:17:57 2018
  OS/Arch:          linux/arm
  Experimental:     false
```

**Comment by sndnvaps** [comment]
split docker-compose.yml to different file
support different platform

**Comment by dperson** [comment]
The read-only startup issues should be resolved in the latest image now. I added the port mapping to the compose file as well.

**Comment by sndnvaps** [comment]
in raspberry pi system is ubuntu mate 16.04 , still use docker-compose 1.18.0 .

**Pull request closed without merging**
